"""
Django settings for mairie project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9+$^vdv77zue(_zqqj-+ayqe=%vf-z=+c#3n9w81@50=lgxav)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'utilisateur.User'

#configurations WhatsApp
WHATSAPP_API_URL = 'https://gate.whapi.cloud/messages/text'
WHATSAPP_API = '2VdWoE5mPUkdwzdp9Il4wS8XuUgYXLB1'
WHATSAPP_NUM = '237655586299'
MAIRE_NOM = 'M. Le Maire'
#WHATSAPP_TOKEN = 'EAAJe9ZBOscCMBPvTFDLpCo8IWCW5qtbOv1pV6lEAYIojs6BSO2Lydp6l61ydIglZCZCYRHtBB2hy3EkfiuISd8rQcdVihpkTRZAG154dZBNVSXYPhlZCNA4y7JIYvEW4swQu99g1RcZAGeRSIngiDAtAyRZBLoz0LjamgfGiFPj13fxDTRcmqrRhThy2QZBKxU27EJLF3jDlpEtofpN9khnT4eX5HJ8gM3E60CPquoPfp1vckHAZDZD'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'utilisateur',
    'mariage',
    'corsheaders',
    'django_crontab',
    'drf_spectacular',
]


# Configuration optionnelle mais recommandée
SPECTACULAR_SETTINGS = {
    'TITLE': 'API Mairie',
    'DESCRIPTION': 'Documentation des services de la mairie',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Permet de regrouper les endpoints par tags (ex: utilisateur, mariage)
    'COMPONENT_SPLIT_PATCH': True,
}

# Configuration des tâches cron
CRONJOBS = [
    # Envoi automatique tous les lundis à 8h du matin
    ('0 8 * * 1', 'mariage.management.commands.envoyer_planning.Command'),
]


# Ajoutez ces configurations pour DRF et JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#CORS_ALLOWED_ORIGINS = [
#    "http://localhost:5173",
#]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']
CORS_ALLOW_METHODS = ['*']

SESSION_COOKIE_SAMESITE = 'None'  # Important!
SESSION_COOKIE_SECURE = True  # True car ngrok utilise HTTPS
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ['https://jessie-tangled-unlethargically.ngrok-free.dev']

ROOT_URLCONF = 'mairie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mairie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mairie',       
        'USER': 'arthur',       
        'PASSWORD': '123456', 
        'HOST': 'localhost',              
        'PORT': '5432',                   
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR/'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
