# Generated by Django 5.2.6 on 2025-09-16 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMariage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Photocopie_CNI', models.BooleanField(default=False)),
                ('Photocopie_acte_naissance', models.BooleanField(default=False)),
                ('Certificat_celibat_mairie', models.BooleanField(default=False)),
                ('Certificat_celibat_autorité', models.BooleanField(default=False)),
                ('Acte_décès_précédent_conjoint', models.BooleanField(blank=True, default=False, null=True)),
                ('Photocopie_ancien_acte_mariage', models.BooleanField(blank=True, default=False, null=True)),
                ('Attestation_divorce', models.BooleanField(blank=True, default=False, null=True)),
                ('Acte_mariages_polygames', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_dossier', models.CharField(max_length=100, unique=True)),
                ('date_celebration', models.DateField()),
                ('heure_celebration', models.TimeField()),
                ('lieu_celebration', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('terminé', 'terminé'), ('annule', 'Annulé')], default='en_attente', max_length=50)),
                ('nom_maire', models.CharField(max_length=100)),
                ('id_marié', models.UUIDField()),
                ('id_mariée', models.UUIDField()),
                ('fait_à', models.CharField(max_length=100)),
                ('fait_le', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=10)),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('nationalité', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('domicile', models.CharField(max_length=255)),
                ('nom_père', models.CharField(max_length=100)),
                ('nom_mère', models.CharField(max_length=100)),
                ('chef_famille_marié', models.CharField(max_length=100)),
                ('chef_famille_mariée', models.CharField(max_length=100)),
                ('nom_temoin_epoux', models.CharField(max_length=100)),
                ('nom_temoin_epouse', models.CharField(max_length=100)),
                ('telephone_epoux', models.CharField(max_length=15)),
                ('telephone_epouse', models.CharField(max_length=15)),
                ('id_témoin1', models.UUIDField(blank=True, null=True)),
                ('id_témoin2', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
