# Generated by Django 5.2.6 on 2025-09-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmariage',
            old_name='Acte_décès_précédent_conjoint',
            new_name='acte_décès_précédent_conjoint',
        ),
        migrations.RenameField(
            model_name='documentmariage',
            old_name='Acte_mariages_polygames',
            new_name='acte_mariages_polygames',
        ),
        migrations.RenameField(
            model_name='documentmariage',
            old_name='Attestation_divorce',
            new_name='attestation_divorce',
        ),
        migrations.RenameField(
            model_name='documentmariage',
            old_name='Certificat_celibat_autorité',
            new_name='certificat_celibat_autorité',
        ),
        migrations.RenameField(
            model_name='documentmariage',
            old_name='Certificat_celibat_mairie',
            new_name='certificat_celibat_mairie',
        ),
        migrations.RenameField(
            model_name='documentmariage',
            old_name='Photocopie_CNI',
            new_name='photocopie_CNI',
        ),
        migrations.RenameField(
            model_name='documentmariage',
            old_name='Photocopie_acte_naissance',
            new_name='photocopie_acte_naissance',
        ),
        migrations.RenameField(
            model_name='documentmariage',
            old_name='Photocopie_ancien_acte_mariage',
            new_name='photocopie_ancien_acte_mariage',
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='id_marié',
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='id_mariée',
        ),
        migrations.AddField(
            model_name='marriage',
            name='infos_mariés',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='marié', to='mariage.personnes'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='id_dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariage.documentmariage'),
        ),
    ]
