# Generated by Django 5.2.6 on 2025-09-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0002_rename_acte_décès_précédent_conjoint_documentmariage_acte_décès_précédent_conjoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnes',
            name='id_témoin1',
        ),
        migrations.RemoveField(
            model_name='personnes',
            name='id_témoin2',
        ),
    ]
