# Generated by Django 5.2.6 on 2025-09-30 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0003_remove_personnes_id_témoin1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmariage',
            name='acte_naissance_enfants_couple',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='documentmariage',
            name='autorisation_mariage_militaire',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='documentmariage',
            name='certificat_capacité_mariage_francais',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='documentmariage',
            name='cni_chef_famille',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentmariage',
            name='cni_temoins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentmariage',
            name='contrat_mariage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='documentmariage',
            name='dix_démi_photos_têtes_collées',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WhatsappNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_destinataire', models.CharField(max_length=15)),
                ('telephone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('envoyé', 'Envoyé'), ('échoué', 'Échoué'), ('en_attente', 'En attente')], default='en_attente', max_length=50)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariage.marriage')),
            ],
        ),
    ]
