# Generated by Django 5.2.6 on 2025-10-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0004_documentmariage_acte_naissance_enfants_couple_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marriage',
            old_name='infos_mariés',
            new_name='infos_maries',
        ),
    ]
