# Generated by Django 5.2.6 on 2025-10-22 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0005_rename_infos_mariés_marriage_infos_maries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Femmes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=10)),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('Arrondoissement_naissance', models.CharField(max_length=100)),
                ('Departement_naissance', models.CharField(max_length=100)),
                ('nationalité', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('domicile', models.CharField(max_length=255)),
                ('nom_père', models.CharField(max_length=100)),
                ('nom_mère', models.CharField(max_length=100)),
                ('chef_famille_mariée', models.CharField(max_length=100)),
                ('nom_temoin_epouse', models.CharField(max_length=100)),
                ('telephone_epouse', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hommes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=10)),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('Arrondoissement_naissance', models.CharField(max_length=100)),
                ('Departement_naissance', models.CharField(max_length=100)),
                ('nationalité', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('domicile', models.CharField(max_length=255)),
                ('nom_père', models.CharField(max_length=100)),
                ('nom_mère', models.CharField(max_length=100)),
                ('chef_famille_marié', models.CharField(max_length=100)),
                ('nom_temoin_epoux', models.CharField(max_length=100)),
                ('telephone_epoux', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='infos_maries',
        ),
        migrations.AddField(
            model_name='marriage',
            name='infos_femme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mariée', to='mariage.femmes'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='infos_homme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='marié', to='mariage.hommes'),
        ),
        migrations.DeleteModel(
            name='Personnes',
        ),
    ]
